#!/usr/bin/env python3
# Minify the Cluso Inspector source (kept in its own repo) into src/cluso.js.hpp as a byte array
# (MSVC caps string literals at 64 KB). Build-time only: uses esbuild via npx.
#   python3 scripts/embed-cluso.py [path/to/cluso-inspector.js]   (default ../cluso-inspector/cluso-inspector.js)
import os, subprocess, sys
here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = os.path.abspath(sys.argv[1] if len(sys.argv) > 1 else os.path.join(here, '..', 'cluso-inspector', 'cluso-inspector.js'))
data = subprocess.run(['npx', '--yes', 'esbuild', src, '--minify', '--charset=utf8', '--target=es2020', '--legal-comments=none'],
                      check=True, capture_output=True).stdout
rows = [', '.join('0x%02x' % b for b in data[i:i + 20]) for i in range(0, len(data), 20)]
out = ['#pragma once', '', '// Generated by scripts/embed-cluso.py (minified %s) - do not edit.' % os.path.basename(src),
       '// Refresh with `make cluso`.', '#include <cstddef>', '',
       'static const unsigned char kClusoJs[] = {'] + ['    ' + r + ',' for r in rows] + ['};',
       'static const size_t kClusoJsLen = %d;' % len(data), '']
open(os.path.join(here, 'src', 'cluso.js.hpp'), 'w').write('\n'.join(out))
print('src/cluso.js.hpp: %d bytes embedded (source %d)' % (len(data), os.path.getsize(src)))
